// ----import lib-----
import Head from "next/head";
import type { AppProps } from "next/app";
import { Provider } from "react-redux";
import "react-quill/dist/quill.snow.css";
// ----import file-----
import "../styles/globals.css";
import store from "../store";
import Navbar from "../components/Navbar";
import Header from "../components/Header";
import AuthenticatedRoute from "../contexts/authenticatedRoute";

function MyApp({ Component, pageProps }: AppProps) {
  try {
    return (
      <Provider store={store}>
        <Head>
          <title>VAIV BO</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/vfast-video.png" />
        </Head>
        <div className="container-page">
          <Navbar />
          <div className="body">
            <Header />
            <div className="body-content w-full h-full px-[10px] tablet:px-[30px] laptop:px-[40px] relative">
              <Component {...pageProps} />
            </div>
          </div>
        </div>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.9.4/Chart.js"></script>
      </Provider>
    );
  } catch (error) {
    console.log(error, "Đây là lỗi nhé");
  }
}

export default MyApp;
